### ISSUE TITLE
npm start doesnt start the app

### ISSUE THREAD

**Issue by Jasnan** [hendriknielaender/slack-jira-estimation-planner#3]
when running `npm start` it throws the following error. 
node version: v18

`/dist/app.js:17511
        throw new Error(msg + "package.json must declare these properties: \n" + missing.join("\n"));
        ^`

```
Error: slack-jira-estimation-planner package.json is not node-pre-gyp ready:
package.json must declare these properties:
binary
```

**Comment by hendriknielaender** [comment]
#5 will fix the issue, sqlite3 needed to be added to the external dependencies in the esbuild config.
